version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - 80:3000
#   environment:
#     - SERVER_PORT=8080
#     - DATABASE_CONNECTIONSTRING=mongodb://mongo:27017/notes
#   volumes:
#     - ./:/usr/src/app
#   command: npm run debug
